### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by dKlee99** [wdecoster/nanocomp#49] opened 2021-09-16 09:19 UTC
Hi, 
I got value error when running NanoComp and not sure what was causing this error. The below is the code and error message respectively! 

Thanks, 
DK
`NanoComp --bam sample1_sorted.bam sample2_sorted.bam sample3_sorted.bam sample4_sorted.bam --outdir NanoComp/`

`/gmi-l1/_90.User_Data/dlekrud456/miniconda3/lib/python3.8/site-packages/pandas/core/arraylike.py:364: RuntimeWarning:

divide by zero encountered in log10

Traceback (most recent call last):
  File "/gmi-l1/_90.User_Data/dlekrud456/miniconda3/bin/NanoComp", line 8, in <module>
    sys.exit(main())
  File "/gmi-l1/_90.User_Data/dlekrud456/miniconda3/lib/python3.8/site-packages/nanocomp/NanoComp.py", line 74, in main
    plots = make_plots(datadf, settings)
  File "/gmi-l1/_90.User_Data/dlekrud456/miniconda3/lib/python3.8/site-packages/nanocomp/NanoComp.py", line 161, in make_plots
    compplots.overlay_histogram_phred(
  File "/gmi-l1/_90.User_Data/dlekrud456/miniconda3/lib/python3.8/site-packages/nanocomp/compplots.py", line 311, in overlay_histogram_phred
    hist_phred.html, hist_phred.fig = plot_overlay_histogram(
  File "/gmi-l1/_90.User_Data/dlekrud456/miniconda3/lib/python3.8/site-packages/nanocomp/compplots.py", line 325, in plot_overlay_histogram
    counts, bins = np.histogram(df.loc[df["dataset"] == d, column],
  File "<__array_function__ internals>", line 5, in histogram
  File "/gmi-l1/_90.User_Data/dlekrud456/miniconda3/lib/python3.8/site-packages/numpy-1.21.1-py3.8-linux-x86_64.egg/numpy/lib/histograms.py", line 793, in histogram
    bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)
  File "/gmi-l1/_90.User_Data/dlekrud456/miniconda3/lib/python3.8/site-packages/numpy-1.21.1-py3.8-linux-x86_64.egg/numpy/lib/histograms.py", line 426, in _get_bin_edges
    first_edge, last_edge = _get_outer_edges(a, range)
  File "/gmi-l1/_90.User_Data/dlekrud456/miniconda3/lib/python3.8/site-packages/numpy-1.21.1-py3.8-linux-x86_64.egg/numpy/lib/histograms.py", line 323, in _get_outer_edges
    raise ValueError(
ValueError: autodetected range of [5.520237922668457, inf] is not finite
`

**Comment by wdecoster** [comment] 2021-09-16 10:21
Hmm, odd. Could you please share the log file as well?

**Comment by dKlee99** [comment] 2021-09-16 11:28
There was only one line present in the log file,
`divide by zero encountered in log10`

Thanks,
DK

**Comment by dKlee99** [comment] 2021-09-16 12:10
Also, seems like it is plotting the same violin plot for different samples.
 
![image](https://user-images.githubusercontent.com/82995207/133609627-6c3cd7d9-5ca0-4f2d-a0bc-92315a04ab8f.png)

**Comment by wdecoster** [comment] 2021-09-16 12:11
> There was only one line present in the log file,
> divide by zero encountered in log10

No that must be a different file, there are lots more things printed in the log file, such as the arguments and python version.


Do you think you can share the data you are working on?

**Comment by dKlee99** [comment] 2021-09-16 12:30
Here is the report from the log file
`2021-09-16 09:35:56,933 NanoComp 1.15.1 started with arguments Namespace(bam=['longread/samtools/N15/N15_chm13_sorted.bam', 'longread/samtools/N15/N15_hg38_sorted.bam', 'longread/samtools/T15/T15_chm13_sorted.bam', 'longread/samtools/T15/T15_hg38_sorted.bam'], barcoded=False, colors=None, cram=None, dpi=100, fasta=None, fastq=None, feather=None, format='png', maxlength=None, minlength=None, names=None, outdir='NanoComp/', path='NanoComp/', pickle=None, plot='violin', prefix='', raw=False, readtype='1D', split_runs=False, store=False, summary=None, threads=4, title=None, tsv_stats=False, ubam=None, verbose=False)
2021-09-16 09:35:56,933 Python version is: 3.8.5 (default, Sep  4 2020, 07:30:14)  [GCC 7.3.0]
2021-09-16 09:35:57,158 Nanoget: Starting to collect statistics from bam file longread/samtools/N15/N15_chm13_sorted.bam.
2021-09-16 09:35:57,159 Nanoget: Starting to collect statistics from bam file longread/samtools/N15/N15_hg38_sorted.bam.
2021-09-16 09:35:57,159 Nanoget: Starting to collect statistics from bam file longread/samtools/T15/T15_hg38_sorted.bam.
2021-09-16 09:35:57,159 Nanoget: Starting to collect statistics from bam file longread/samtools/T15/T15_chm13_sorted.bam.
2021-09-16 09:35:57,386 Nanoget: Bam file longread/samtools/T15/T15_hg38_sorted.bam contains 6161475 mapped and 638488 unmapped reads.
2021-09-16 09:35:57,387 Nanoget: Bam file longread/samtools/T15/T15_chm13_sorted.bam contains 5653470 mapped and 686946 unmapped reads.
2021-09-16 09:35:57,394 Nanoget: Bam file longread/samtools/N15/N15_hg38_sorted.bam contains 10503663 mapped and 1075766 unmapped reads.
2021-09-16 09:35:57,397 Nanoget: lots of contigs (>100) or --huge, not running in separate processes
2021-09-16 09:35:57,398 Nanoget: lots of contigs (>100) or --huge, not running in separate processes
2021-09-16 09:35:57,416 Nanoget: Bam file longread/samtools/N15/N15_chm13_sorted.bam contains 9712433 mapped and 1144707 unmapped reads.
2021-09-16 14:15:52,504 Nanoget: bam longread/samtools/T15/T15_chm13_sorted.bam contains 4863729 primary alignments.
2021-09-16 14:15:56,345 Reduced DataFrame memory usage from 705.5621194839478Mb to 580.3249568939209Mb
2021-09-16 14:19:42,627 Nanoget: bam longread/samtools/T15/T15_hg38_sorted.bam contains 5284229 primary alignments.
2021-09-16 14:19:45,775 Reduced DataFrame memory usage from 766.4652690887451Mb to 630.4005651473999Mb
2021-09-16 16:40:37,313 Nanoget: bam longread/samtools/N15/N15_chm13_sorted.bam contains 8302617 primary alignments.
2021-09-16 16:40:43,204 Reduced DataFrame memory usage from 1210.0954055786133Mb to 996.3096055984497Mb
2021-09-16 16:43:41,528 Nanoget: bam longread/samtools/N15/N15_hg38_sorted.bam contains 8963422 primary alignments.
2021-09-16 16:43:47,491 Reduced DataFrame memory usage from 1306.160912513733Mb to 1075.3599081039429Mb
2021-09-16 16:44:04,746 Nanoget: Gathered all metrics of 27413997 reads
2021-09-16 16:44:04,750 Using sequenced read lengths for plotting.
2021-09-16 16:45:20,811 NanoComp: Creating barplots for number of reads and total throughput.
2021-09-16 16:45:27,221 Saved NanoComp/NanoComp_number_of_reads  as png (or png for --legacy)
2021-09-16 16:45:35,598 Saved NanoComp/NanoComp_total_throughput  as png (or png for --legacy)
2021-09-16 16:45:37,324 Saved NanoComp/NanoComp_N50  as png (or png for --legacy)
2021-09-16 16:45:37,399 NanoComp: Creating violin plot for lengths.
2021-09-16 16:45:40,492 Saved NanoComp/NanoComp_lengths_violin  as png (or png for --legacy)
2021-09-16 16:45:40,551 NanoComp: Creating violin plot for log length.
2021-09-16 16:45:43,533 Saved NanoComp/NanoComp_log_length_violin  as png (or png for --legacy)
2021-09-16 16:45:43,585 NanoComp: Creating violin plot for quals.
2021-09-16 16:45:46,057 Saved NanoComp/NanoComp_quals_violin  as png (or png for --legacy)
2021-09-16 16:45:46,115 NanoComp: Creating violin plot for percentIdentity.
2021-09-16 16:45:49,523 Saved NanoComp/NanoComp_percentIdentity_violin  as png (or png for --legacy)
2021-09-16 16:45:51,251 Saved NanoComp/NanoComp_OverlayHistogram_Identity  as png (or png for --legacy)
2021-09-16 16:45:51,350 autodetected range of [5.520237922668457, inf] is not finite
Traceback (most recent call last):
  File "/gmi-l1/_90.User_Data/dlekrud456/miniconda3/lib/python3.8/site-packages/nanocomp/NanoComp.py", line 74, in main
    plots = make_plots(datadf, settings)
  File "/gmi-l1/_90.User_Data/dlekrud456/miniconda3/lib/python3.8/site-packages/nanocomp/NanoComp.py", line 161, in make_plots
    compplots.overlay_histogram_phred(
  File "/gmi-l1/_90.User_Data/dlekrud456/miniconda3/lib/python3.8/site-packages/nanocomp/compplots.py", line 311, in overlay_histogram_phred
    hist_phred.html, hist_phred.fig = plot_overlay_histogram(
  File "/gmi-l1/_90.User_Data/dlekrud456/miniconda3/lib/python3.8/site-packages/nanocomp/compplots.py", line 325, in plot_overlay_histogram
    counts, bins = np.histogram(df.loc[df["dataset"] == d, column],
  File "<__array_function__ internals>", line 5, in histogram
  File "/gmi-l1/_90.User_Data/dlekrud456/miniconda3/lib/python3.8/site-packages/numpy-1.21.1-py3.8-linux-x86_64.egg/numpy/lib/histograms.py", line 793, in histogram
    bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)
  File "/gmi-l1/_90.User_Data/dlekrud456/miniconda3/lib/python3.8/site-packages/numpy-1.21.1-py3.8-linux-x86_64.egg/numpy/lib/histograms.py", line 426, in _get_bin_edges
    first_edge, last_edge = _get_outer_edges(a, range)
  File "/gmi-l1/_90.User_Data/dlekrud456/miniconda3/lib/python3.8/site-packages/numpy-1.21.1-py3.8-linux-x86_64.egg/numpy/lib/histograms.py", line 323, in _get_outer_edges
    raise ValueError(
ValueError: autodetected range of [5.520237922668457, inf] is not finite
`
I used pacbio clr as platform and samples are gastric tumor-normal paired sample. Briefly, I want to compare hg38 and new human genome reference chm13 and also am working on SV calling pipeline using tumor specific kmer based approach. Thank you so much for your comment! 

Best,
DK

**Comment by wdecoster** [comment] 2021-09-16 13:49
Can you show me just a single read of a bam file?

**Comment by dKlee99** [comment] 2021-09-16 15:06
Sure, is this what you were asking?

Thank you so much! 

![image](https://user-images.githubusercontent.com/82995207/133636964-56dd2ed4-6eed-4ba1-a588-8270e3322f60.png)

**Comment by wdecoster** [comment] 2021-09-16 16:54
Yes, that's helpful. As I suspected - no variation in quality scores. I will fix this soon

**Comment by dKlee99** [comment] 2021-09-17 01:32
Thank you so much! 

Indeed, when I ran NanoStats no read quality appeared. Is this also due to no quality scores in bam file? 
![image](https://user-images.githubusercontent.com/82995207/133709470-947c8ffb-3b4f-4036-89a0-b6d0a747cbfb.png)

DK

**Comment by wdecoster** [comment] 2021-09-17 06:13
Correct - your FASTQ/BAM file has just `!` as quality strings, meaning a quality score of 0. I don't know if that is always the case for PacBio data, but I wouldn't be surprised if this could cause you problems with other programs too. But this problem in NanoComp should be fixed regardless.

**Comment by dKlee99** [comment] 2021-09-17 07:46
Thanks a lot! turned out this is the general feature of pacbio clr data. Would you please let me know when it's fixed? I really appreciate your help a lot! 

Best,
DK

**Comment by wdecoster** [comment] 2021-09-24 14:38
Hi,

It seems I cannot reproduce this. Could you maybe share your input file? I tried making an artificial file to replicate yours, but it just works.

Thanks,
Wouter

**Comment by dKlee99** [comment] 2021-09-24 14:55
Hi, 

Sure! Thank you so much for your time. If that's the case, I will try to rerun and see if I get the same error message. I will send the input file to your email. 

Thank you, 
DK

**Comment by dKlee99** [comment] 2021-09-25 03:34
Hi,

I tried to rerun it but still got the same error message. Thank you.

`divide by zero encountered in log10
Traceback (most recent call last):
  File "/gmi-l1/_90.User_Data/dlekrud456/miniconda3/bin/NanoComp", line 8, in <module>
    sys.exit(main())
  File "/gmi-l1/_90.User_Data/dlekrud456/miniconda3/lib/python3.8/site-packages/nanocomp/NanoComp.py", line 74, in main
    plots = make_plots(datadf, settings)
  File "/gmi-l1/_90.User_Data/dlekrud456/miniconda3/lib/python3.8/site-packages/nanocomp/NanoComp.py", line 161, in make_plots
    compplots.overlay_histogram_phred(
  File "/gmi-l1/_90.User_Data/dlekrud456/miniconda3/lib/python3.8/site-packages/nanocomp/compplots.py", line 311, in overlay_histogram_phred
    hist_phred.html, hist_phred.fig = plot_overlay_histogram(
  File "/gmi-l1/_90.User_Data/dlekrud456/miniconda3/lib/python3.8/site-packages/nanocomp/compplots.py", line 325, in plot_overlay_histogram
    counts, bins = np.histogram(df.loc[df["dataset"] == d, column],
  File "<__array_function__ internals>", line 5, in histogram
  File "/gmi-l1/_90.User_Data/dlekrud456/miniconda3/lib/python3.8/site-packages/numpy-1.21.1-py3.8-linux-x86_64.egg/numpy/lib/histograms.py", line 793, in histogram
    bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)
  File "/gmi-l1/_90.User_Data/dlekrud456/miniconda3/lib/python3.8/site-packages/numpy-1.21.1-py3.8-linux-x86_64.egg/numpy/lib/histograms.py", line 426, in _get_bin_edges
    first_edge, last_edge = _get_outer_edges(a, range)
  File "/gmi-l1/_90.User_Data/dlekrud456/miniconda3/lib/python3.8/site-packages/numpy-1.21.1-py3.8-linux-x86_64.egg/numpy/lib/histograms.py", line 323, in _get_outer_edges
    raise ValueError(
ValueError: autodetected range of [5.450179100036621, inf] is not finite`

Best,
DK

**Comment by wdecoster** [comment] 2021-09-27 09:18
Hi DK,

I received your file, but could again not reproduce the issue on my machine. Could you let me know which version of numpy you are using?

Wouter

**Comment by abdul-voltalabs** [comment] 2021-10-01 02:15
Hello, I am having the similar issue; Violin plot showing same data across 4 different samples. This is only for Violin or Box plots. The column plots, histogram, line plots are fine and show 4 different data. Has this been resolved?

<img width="647" alt="Screen Shot 2021-09-30 at 10 13 53 PM" src="https://user-images.githubusercontent.com/91698386/135555130-3097c365-b569-499e-
<img width="1110" alt="Screen Shot 2021-09-30 at 10 14 19 PM" src="https://user-images.githubusercontent.com/91698386/135555168-b5db826d-51b9-4794-b022-434f4e6d9eff.png">
b48d-7e6f29f7305c.png">

Thanks, 
Abdul

**Comment by wdecoster** [comment] 2021-10-01 07:57
Hi Abdul,

Thanks for letting me know. I have indeed identified a bug here and solved it in NanoComp v.16.0. That version should soon be available on PyPI and bioconda. My apologies! This however won't solve the original problem (the ValueError) of dKlee99.

Wouter

**Comment by abdul-voltalabs** [comment] 2021-10-01 18:06
Great - thank you. Was able to get it resolved through version 1.16.0. Thanks Wouter!

**Comment by wdecoster** [comment] 2021-11-09 09:13
This ValueError should be fixed now in v1.16.1!

**Closed** 2021-11-09 09:13 UTC
